default:
  dora_dir: ./sessions
  partitions:
    global: debug
    team: debug
  reference_dir: ./sessions
darwin: # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: ./sessions
  partitions:
    global: debug
    team: debug
  reference_dir: ./sessions
